name: Code style check

# Use:
# LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml
# once their lint-checker has been updated

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Lint
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: "./"
          extensions: "h,c"
          clangFormatVersion: 17
